/**
 * TỦ SÁCH HAY - Catalog Sách & Tri Thức Tuyển Chọn
 * Định nghĩa danh mục toàn bộ sách trong kho tri thức
 */

window.BOOKS_CATALOG = [
  {
    id: "5-phut-thuoc-bai",
    title: "5 Phút Thuộc Bài",
    author: "Nguyễn Phùng Phong & Brahmi Nguyễn",
    category: "Phương pháp học tập",
    categorySlug: "ky-nang",
    tag: "Đã có bản đọc web (100% Ảnh gốc)",
    status: "ready",
    dataFile: "data/books/5-phut-thuoc-bai.js",
    totalChapters: 29,
    coverBadge: "🐘",
    coverTheme: "vibrant-amber",
    year: "Tái bản lần 6",
    shortDesc: "Học nhẹ nhàng - Nhớ dễ dàng: Quy trình 6-3-4, mã hóa 100 con số 00-99, 26 chữ cái và 11 phương pháp siêu trí nhớ kèm 189 trang tranh ảnh gốc.",
    highlights: ["189 trang tranh ảnh gốc siêu nét", "Quy trình 6-3-4 học thông minh", "Mã hóa 100 số & 11 phương pháp nhớ"]
  },
  {
    id: "tri-tue-khong-tu",
    title: "Trí Tuệ Khổng Tử",
    author: "Khổng Tử (Biên soạn: NXB Văn Hóa - Thông Tin)",
    category: "Triết học Á Đông",
    categorySlug: "triet-hoc",
    tag: "Đã có bản đọc web (100%)",
    status: "ready", // ready to read on web
    dataFile: "data/books/tri-tue-khong-tu.js",
    totalChapters: 91,
    coverBadge: "孔",
    coverTheme: "eastern-red",
    year: "Kinh điển",
    shortDesc: "Đúc kết 91 điển tích và câu chuyện nhân sinh, đạo trị quốc, phép tu thân và thuật xử thế uyển chuyển của bậc Vạn thế sư biểu.",
    highlights: ["91 câu chuyện & điển tích", "Phân tích lời bình sâu sắc", "Tu thân, Tề gia, Xử thế"]
  },
  {
    id: "doc-sach-sieu-toc",
    title: "Đọc Sách Siêu Tốc",
    author: "Christian Grüning",
    category: "Phương pháp học tập",
    categorySlug: "ky-nang",
    tag: "Khuyến nghị đọc đầu tiên",
    status: "ready-soon",
    pdfPath: "../DAY DOC NHANH/Doc_sach_sieu_toc-Christian_Gruning.pdf",
    totalChapters: "5 Phần",
    coverBadge: "⚡",
    coverTheme: "vibrant-amber",
    year: "Kỹ năng vàng",
    shortDesc: "Kỹ thuật Visual Reading đột phá: mở rộng tầm mắt, nắm bắt cấu trúc sách, đọc nhanh gấp 3 lần và ghi nhớ sâu bằng Mindmap.",
    highlights: ["Mở rộng trường nhìn mắt", "Kỹ thuật đọc lướt nắm ý", "Sơ đồ tư duy ghi nhớ"]
  },
  {
    id: "day-con-lam-giau-tap-1",
    title: "Dạy Con Làm Giàu (Tập 1)",
    author: "Robert T. Kiyosaki",
    category: "Tài chính & Làm giàu",
    categorySlug: "tai-chinh",
    tag: "Kinh điển tài chính",
    status: "ready-soon",
    pdfPath: "../RICH/DAY CON LAM GIAU/Day con lam giau tap 1.pdf",
    totalChapters: "6 Bài học",
    coverBadge: "💰",
    coverTheme: "royal-gold",
    year: "Best-seller",
    shortDesc: "Để không phải làm việc vì tiền – Khai mở tư duy về Tài sản và Tiêu sản, Kim tứ đồ và con đường thoát khỏi vòng luẩn quẩn cơm áo gạo tiền.",
    highlights: ["Tài sản vs Tiêu sản", "Người giàu không làm việc vì tiền", "Hiểu biết về tài chính"]
  },
  {
    id: "dung-bao-gio-di-an-mot-minh",
    title: "Đừng Bao Giờ Đi Ăn Một Mình",
    author: "Keith Ferrazzi",
    category: "Phát triển bản thân",
    categorySlug: "phat-trien",
    tag: "Nghệ thuật kết nối",
    status: "ready-soon",
    pdfPath: "../PHAT TRIEN BAN THAN/dung-bao-gio-di-an-mot-minh.pdf",
    totalChapters: "31 Chương",
    coverBadge: "🤝",
    coverTheme: "emerald-green",
    year: "Kỹ năng sống",
    shortDesc: "Bí quyết xây dựng và duy trì mạng lưới quan hệ chân thành, tạo giá trị thực sự cho người khác để cùng nhau phát triển vững bền.",
    highlights: ["Kết nối chân thành", "Cho đi trước nhận lại sau", "Xây dựng thương hiệu cá nhân"]
  },
  {
    id: "bao-mat-nhap-mon-developer",
    title: "Bảo Mật Nhập Môn Cho Developer",
    author: "Phạm Huy Hoàng (Tôi Đi Code Dạo)",
    category: "Công nghệ thông tin",
    categorySlug: "cong-nghe",
    tag: "Thực chiến IT",
    status: "ready-soon",
    pdfPath: "../Bảo mật nhập môn cho Developer - Phạm Huy Hoàng.pdf",
    totalChapters: "12 Chương",
    coverBadge: "🛡️",
    coverTheme: "tech-cyan",
    year: "Công nghệ",
    shortDesc: "Hiểu rõ các lỗ hổng bảo mật kinh điển: SQL Injection, XSS, CSRF, Password hashing qua lăng kính dí dỏm, thực tế và dễ hiểu.",
    highlights: ["SQL Injection & XSS", "Quản lý phiên & CSRF", "Tư duy phòng thủ cho lập trình viên"]
  },
  {
    id: "bi-mat-tu-duy-trieu-phu",
    title: "Bí Mật Tư Duy Triệu Phú",
    author: "T. Harv Eker",
    category: "Tài chính & Làm giàu",
    categorySlug: "tai-chinh",
    tag: "Tư duy thịnh vượng",
    status: "ready-soon",
    pdfPath: "../RICH/Bi mat tu duy trieu phu - T. Harv Eker.pdf",
    totalChapters: "17 Hồ sơ tư duy",
    coverBadge: "💎",
    coverTheme: "deep-purple",
    year: "Tư duy đột phá",
    shortDesc: "Cài đặt lại nhiệt kế tài chính trong tâm thức: 17 sự khác biệt căn bản trong cách người giàu, người nghèo và giới trung lưu suy nghĩ.",
    highlights: ["Nhiệt kế tài chính", "17 hồ sơ tư duy thịnh vượng", "Kiểm soát tâm trí về tiền"]
  },
  {
    id: "phuong-phap-ghi-nho-dinh-cao",
    title: "Phương Pháp Ghi Nhớ Đỉnh Cao",
    author: "Eran Katz (Kỷ lục gia Guinness)",
    category: "Phương pháp học tập",
    categorySlug: "ky-nang",
    tag: "Khai mở trí nhớ",
    status: "ready-soon",
    pdfPath: "../6039-phuong-phap-ghi-nho-dinh-cao-thuviensach.vn.pdf",
    totalChapters: "15 Chương",
    coverBadge: "🧠",
    coverTheme: "vibrant-amber",
    year: "Trí nhớ siêu phàm",
    shortDesc: "Tuyệt chiêu ghi nhớ tên người, con số, sự kiện và ngoại ngữ của người Do Thái – Biến não bộ thành cỗ máy lưu trữ phi thường.",
    highlights: ["Kỹ thuật La Mã Cổ Đại", "Ghi nhớ chữ số & sự kiện", "Phương pháp người Do Thái"]
  },
  {
    id: "hoc-kinh-dich",
    title: "Học Kinh Dịch & Triết Lý Biến Dịch",
    author: "Cổ thư & Nhà nghiên cứu dịch học",
    category: "Triết học Á Đông",
    categorySlug: "triet-hoc",
    tag: "Đạo trời đất",
    status: "ready-soon",
    pdfPath: "../KINH DICH/Hoc kinh dich.pdf",
    totalChapters: "64 Quẻ dịch",
    coverBadge: "☯",
    coverTheme: "eastern-red",
    year: "Kinh điển tối thượng",
    shortDesc: "Khám phá quy luật vận động của âm dương, ngũ hành và vạn vật trong vũ trụ. Đạo ứng biến và thuật xử thế khi gặp thời bĩ thái.",
    highlights: ["Âm Dương & Ngũ Hành", "64 Quẻ tượng & Hào từ", "Đạo tùy thời ứng biến"]
  }
];
